### ISSUE TITLE
A way to change plugin settings?

### ISSUE THREAD

**Issue by Yodzorah** [erf/vis-plug#2]
# Without Plug

```lua
local dothis = require('plugins/dothis')
local dothat = require('plugins/dothat')

dothis.var = 'value'
dothat.var = 'value'
```

# With Plug

```lua
local plug = require('plugins/vis-plug')
plug.init(plugins)

-- impossible to change plugin variables
```

# Desired behaviour with Plug

```lua
local plug = require('plugins/vis-plug')
plug.init(plugins)

plug.dothis.var = 'value'
plug.dothat.var = 'value'
```

**Comment by erf** [comment]
Hi, thanks for the feedback. Could perhaps add an optional name for "dothis" and "dothat" to plugins which you pass to init, which you could later access via "plug.plugins.dothis|dothat" (after init). My macbook is in repair right now, but can look at it when i get it back.

**Comment by erf** [comment]
Or, perhaps return them as an array in a callback.

**Comment by Yodzorah** [comment]
Would be nice to have a way to assign custom names to plugins by stating it in the init array. Much more usable than somehow naming plugins after their directories or some other automated method of naming.

**Comment by erf** [comment]
Fixed via 64f8b10c9f8aa7b960eb9c57b2ace05762f2281c

@Yodzorah let me know if it works for you

**Comment by Yodzorah** [comment]
Right after opening `vis`:

```
/home/zorg/.config/vis/plugins/vis-plug/init.lua:86: attempt to concatenate a nil value (local 'file')
```

**Comment by Yodzorah** [comment]
Right after opening `vis`:

```
/home/username/.config/vis/plugins/vis-plug/init.lua:86: attempt to concatenate a nil value (local 'file')
```

**Comment by erf** [comment]
Now you always have to use a table for the table value, e.g. { init } or { init, cursors }. 

If that does not work, please show me a minimal `visrc.lua` file which creates that error.

**Comment by erf** [comment]
I updated the plugin to support both string and table now.
