### ISSUE TITLE
Had to change xargs commands

### ISSUE THREAD

**Issue by ghost** [erf/vis-plug#21]
I am running `vis` and `vis-plug` on OpenBSD and I had to change the xargs commands.

From `xargs -P0` to `xargs -P1`. Without it I got the `xargs: -P 0: too small` error message.

Do you want me to create a pull request?

**Comment by erf** [comment]
In the manual on macOS is says:

```
  -P maxprocs
             Parallel mode: run at most maxprocs invocations of utility at once.  If maxprocs is set
             to 0, xargs will run as many processes as possible.
```

So i would like to use as many processs as possible.. Do you have something similar on OpenBSD?

**Comment by ghost** [comment]
Ah okay, I get it now. I thought 0 means none. I don't think the OpenBSD xargs has that option. See [here](https://man.openbsd.org/xargs).

**Comment by erf** [comment]
You could perhaps check for the OS name and set the P to 1 (or more) if BSD. Or check for the number of processors on the system if possible.

**Comment by erf** [comment]
@ndalliard I've removed the use of xargs now, and instead just run a set of shell commands in the background
