### ISSUE TITLE
question/feature request: adding multiple themes from one repo

### ISSUE THREAD

**Issue by hholst80** [erf/vis-plug#28]
How do I add a repo that contains several color schemes as a bundle?

Use case:

https://github.com/rokf/vis-themes

I can add an individual theme like this:

```
{ 'rokf/vis-themes', theme = true, file = 'oil6' }
```

However, that will not allow me to switch later to say "darkest-space" which is part of the same repo.  Switching between multiple themes from one repo would be pretty handy, for instance, if different themes are used per file type.

**Comment by erf** [comment]
I think you just need to change the 'file' in the config file or you can call the 'set theme' command with the theme you want, but you also need to add the name of the plugin. e.g. `:set theme vis-themes/darkest-space`

**Comment by erf** [comment]
Closing this for now. I think it works for now as a minimal plugin. Feel free to add a more specific use case or make a PR.
