### ISSUE TITLE
Make it work for themes if it's consistent with the vis philosophy

### ISSUE THREAD

**Issue by Yodzorah** [erf/vis-plug#3]
Add an ability to add themes into `themes` directory, while still being able to add plugins into `plugins` directory. Maybe split the init array into two parts: `plugins` (which would be identical to what we pass to `init` now) and `themes`? I tried to pass themes as plugins, but when I executed `:set theme <theme_name>`, `vis` throwed errors at me meaning that it was only looking in the `themes` directories (which makes sense and, imo, is better behaviour than when it worked in `vim`).

Don't have much experience or deep understanding of `vis`, so I don't know if it's a good idea in terms of `vis` philosophy, general consistency and logic. Is it a good way of handling themes or it's part of what was messy about `vim` and its popular plugins? Like when plugin managers were also managing themes? Maybe it would be better to not implement it and create a separate plugin for themes with themes-specific features like live editing?

**Comment by erf** [comment]
Great idea. Will look into it. Adding a separate parameter with themes which would add it to the "themes" folder i think would make sense. This plugin is experimental, but the Lua api is there for experimenting and i think it may make sense for some people to group it like this (and replicating the vim plug functionality). For others they would just add the lua plugins and themes as part of their dotfiles repo. With this pluging it is easier to keep up to date with plugins, but we can't guarantee third party plugins and themes are available. I try to use vis default folders, but i hope someone will correct me if this is wrong.

**Comment by erf** [comment]
Fixed via d43c789185bba4883316c24b07e09b0cc7559053

@Yodzorah let me know if it works for you
