### ISSUE TITLE
Use `XDG_DATA_HOME` for plugins

### ISSUE THREAD

**Issue by unrealapex** [erf/vis-plug#33]
The XDG spec describes `XDG_CACHE_HOME` as "where user-specific *non-essential* (cached) data should be written". `XDG_DATA_HOME` would be a more proper place to store plugin files. Using the latter would be better, however, backwards compatibility or a warning would need to be provided for people who choose to keep their plugins in the former location.

**Comment by erf** [comment]
I use the `XDG_CACHE_HOME` as the plugins you install via `vis-plug` should be easily installed or delete and they are not meant to be stored on a permanent basis. If you feel `XDG_DATA_HOME` would be better , can you explain why ?

**Comment by unrealapex** [comment]
My apologies for not being clear.

`XDG_DATA_HOME` is defined as a location for [more persistent program data](https://specifications.freedesktop.org/basedir-spec/latest/#basics). I object to using `XDG_CACHE_HOME` because as the name implies, it is used for storing cache files. Additionally, contributing to Neovim's plugin ecosystem, I have found most of its plugin managers also use `XDG_DATA_HOME`.

**Comment by erf** [comment]
I think you might be right in using `XDG_DATA_HOME` by default. We could also introduce a custom environment variable like `VIS_PLUG_HOME`. We should still check for `XDG_CACHE_HOME` as we've used that before i think.

**Comment by erf** [comment]
Fixed in 98451c69ca1c5e65d41035cf5721dbff72dcd125

**Comment by erf** [comment]
I've changed my mind regarding `XDG_DATA_HOME` and will use `XDG_CACHE_HOME` or the custom `VIS_PLUG_HOME` to store plugin files. 

The plugins are not exactly "user-specific files" and are not meant to be stored permanently and can easily be downloaded again when opening vis or using plug-install.
