### ISSUE TITLE
Add `dev` option to load plugins locally

### ISSUE THREAD

**Issue by unrealapex** [erf/vis-plug#34]
Having a `dev` option that loads a plugin locally instead of downloading it would be convenient for plugin testing. By default `dev` should load from a common path like `~/projects` or from an arbitrary path if `dev` is assigned a path.

**Comment by erf** [comment]
You can make a symbolic link now from the cache folder to your plugin directory to test things out. I'm not sure about being able to add support for local paths as it might make things more complex. If you would like this feature i suggest first make a more comprehensive explanation on how this should work with the current config. Also if you can make a PR to demonstrate this without complicating things too much i might be on board with this.

**Comment by erf** [comment]
I will close this for now. If you have an improved explanation for how this should work please reopen - especially if you intend to work on this and make a PR.
