### ISSUE TITLE
:plug-uninstall to delete repos for not required plugins

### ISSUE THREAD

**Issue by Yodzorah** [erf/vis-plug#4]
Would be nice to have an ability to locally delete all repos for not required plugins. It would mean that uninstalling a bunch of plugins can be done by changing `plug` settings and executing a command to uninstall, which seems like the kind of job `plug` ought to do.

**Comment by erf** [comment]
I think i rather not have vis-plug be responsible for deleting files.

**Comment by Yodzorah** [comment]
@erf, well, `plug` is sure responsible for creating them. Maybe only delete repos if there are no changes to them at all? Besides, that's why I'm asking for a separate command `plug-uninstall` - it will only delete anything if the user's asked for it. IIRC, `plug` for vim does that on `update` or `install`, which is ten times worse.

**Comment by erf** [comment]
yeah, but it's much worse do delete something than to add something, i.e. if there was a bug in the code and something was deleted by mistake

**Comment by erf** [comment]
I added commands `vis-delete` and `vis-clean` now, which deletes either a single plugin by name from disk, or all plugins in configuration from disk.
